name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-16.04, windows-latest]
        rust: [stable, nightly]

    steps:
    - name: Set up a Rust toolchain
      uses: hecrj/setup-rust-action@v1.3.1
      with:
        rust-version: ${{ matrix.rust }}
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: cargo build --verbose

    - name: Build release
      run: cargo build --release --verbose

    - if: matrix.os == 'ubuntu-*'
      name: Strip release
      run: strip target/release/yps

    - name: Run tests
      run: cargo test --verbose

    - name: Upload Artifacts
      uses: actions/upload-artifact@v1
      with:
        name: yps_rust-${{ matrix.rust }}-${{ matrix.os }}
        path: target/release/yps*
